ManagementApartments/Controllers/ApartmentsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ManagementApartments.Data.Models;
using ManagementApartments.Data.Service.Interface;
using X.PagedList;
using ManagementApartments.Data.Config;
using Microsoft.AspNetCore.Http;
using System.IO;
using ManagementApartments.Data.DTO;
using AutoMapper;

namespace ManagementApartments.Controllers
{
    public class ApartmentsController : Controller
    {
        private readonly IApartmentsService apartmentService;
        private readonly IMapper mapper;

        public ApartmentsController(IApartmentsService apartmentService,IMapper mapper)
        {
            this.apartmentService = apartmentService;
            this.mapper = mapper;
        }

        // GET: Apartments
        public IActionResult Index(int page = 1)
        {
            IPagedList<Apartment> apartments = apartmentService.GetByPage(page, 9, this.User.GetLoggedInUserId<string>());
            return View(apartments);
        }

        // GET: Apartments/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>(); 
            return View();
        }

        // POST: Apartments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Description,ApartmentPrice,RentPrice,Area")] ApartmentCreateDTO apartment)
        {
            if (ModelState.IsValid)
            {
                apartmentService.Create(apartment, this.User.GetLoggedInUserId<string>());
                return RedirectToAction(nameof(Index));
            }

            return View(mapper.Map<ApartmentCreateDTO, Apartment>(apartment));
        }

        public ActionResult SaveImage(IFormFile file, int apartmentId)
        {
            if (file != null)
            {
                string extension = Path.GetExtension(file.FileName);

                List<string> allowedExtensions = new List<string>()
                {
                    ".png", ".bmp", ".svg", ".jpg", ".jpeg", ".gif"
                };

                if (!allowedExtensions.Contains(extension))
                {
                    return Json(new SaveImageFeedbackDTO
                    {
                        StatusSuccess = false,
                        Message = "Only .png .bmp .svg .jpg .jpeg .gif file types are allowed",
                        Title = "File type not supported."
                    });
                }
                string logoAsBase64 = this.apartmentService.SaveImage(file, apartmentId);

                return Json(new SaveImageFeedbackDTO
                {
                    StatusSuccess = true,
                    LogoAsBase64 = logoAsBase64
                });
            }
            else
            {
                return Json(new SaveImageFeedbackDTO
                {
                    StatusSuccess = false,
                    Message = "Only .png .bmp .svg .jpg .jpeg .gif file types are allowed",
                    Title = "File type not supported."
                });
            }
        }

        public ActionResult DeleteLogo(int apartmentId)
        {
            this.apartmentService.DeleteLogo(apartmentId);

            return Json(true);
        }

        // GET: Apartments/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apartment = this.apartmentService.Get(id??0, this.User.GetLoggedInUserId<string>());
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(apartment);
        }

        // POST: Apartments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Description,ApartmentPrice,RentPrice,Area")] ApartmentCreateDTO apartmentDto)
        {
            if (id != apartmentDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                apartmentService.Edit(apartmentDto, this.User.GetLoggedInUserId<string>());
                return RedirectToAction(nameof(Index));
            }
            
            return View(apartmentService.Get(apartmentDto.Id, this.User.GetLoggedInUserId<string>()));
        }

        // GET: Apartments/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apartment = this.apartmentService.Get(id ?? 0, this.User.GetLoggedInUserId<string>()); 
            return View(apartment);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            apartmentService.Remove(id, this.User.GetLoggedInUserId<string>());
            return RedirectToAction(nameof(Index));
        }
    }
}

ManagementApartments/Controllers/TenantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManagementApartments.Data;
using ManagementApartments.Data.Models;
using ManagementApartments.Data.Service.Interface;
using ManagementApartments.Data.Config;

namespace ManagementApartments.Controllers
{
    public class TenantsController : Controller
    {
        private readonly ITenantsService tenantsService;

        public TenantsController(ITenantsService tenantsService)
        {
            this.tenantsService = tenantsService;
        }

        // GET: Tenants
        public IActionResult Index()
        {
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(tenantsService.GetList(this.User.GetLoggedInUserId<string>()));
        }

        // GET: Tenants/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View();
        }

        // POST: Tenants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,FirstName,LastName,PhoneNumber,ApplicationUserId")] Tenant tenant)
        {
            if (ModelState.IsValid)
            {
                tenantsService.Create(tenant);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(tenant);
        }

        // GET: Tenants/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tenant = tenantsService.Get(id??0);
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(tenant);
        }

        // POST: Tenants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,FirstName,LastName,PhoneNumber,ApplicationUserId")] Tenant tenant)
        {
            if (id != tenant.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                tenantsService.Update(tenant);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(tenant);
        }

        // GET: Tenants/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tenant = tenantsService.Get(id??0);
            if (tenant == null)
            {
                return NotFound();
            }

            return View(tenant);
        }

        // POST: Tenants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            tenantsService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ManagementApartments/Controllers/WorkingContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManagementApartments.Data;
using ManagementApartments.Data.Models;
using ManagementApartments.Data.Service.Interface;
using ManagementApartments.Data.Config;

namespace ManagementApartments.Controllers
{
    public class WorkingContactsController : Controller
    {
        private readonly ManagementApartmentDbContext _context;
        private readonly IWorkingContactService workingContactService;

        public WorkingContactsController(ManagementApartmentDbContext context, IWorkingContactService workingContactService)
        {
            _context = context;
            this.workingContactService = workingContactService;
        }

        // GET: WorkingContacts
        public IActionResult Index()
        {
            return View(workingContactService.GetList(this.User.GetLoggedInUserId<string>()));
        }

        // GET: WorkingContacts/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>(); 
            return View();
        }

        // POST: WorkingContacts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,PhoneNumber,ApplicationUserId")] WorkingContact workingContact)
        {
            if (ModelState.IsValid)
            {
                workingContactService.Create(workingContact);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(workingContact);
        }

        // GET: WorkingContacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workingContact = workingContactService.Get(id??0);

            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(workingContact);
        }

        // POST: WorkingContacts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,PhoneNumber,ApplicationUserId")] WorkingContact workingContact)
        {
            if (id != workingContact.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                workingContactService.Update(workingContact);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(workingContact);
        }

        // GET: WorkingContacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workingContact = workingContactService.Get(id ?? 0);
            if (workingContact == null)
            {
                return NotFound();
            }

            return View(workingContact);
        }

        // POST: WorkingContacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            workingContactService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

ManagementApartments/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ManagementApartments.Data.Models

@inject SignInManager<ApplicationUser> SigninManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Light Apartment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert/lib/sweet-alert.css" rel="stylesheet" />
    <link href="~/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark @(ViewBag.ContainerFluid == true ? "": "bg-dark") border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Light Apartment</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SigninManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Apartments" asp-action="Index">Apartments</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Tenants" asp-action="Index">Tenants</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="WorkingContacts" asp-action="Index">Working Contacts</a>
                            </li>
                        }
                        @*@if (SigninManager.IsSignedIn(User) && User.IsInRole(UserRoles.ADMIN))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Admin
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                                        <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="MuscleLoad" asp-action="Index">MuscleLoad</a>
                                    </div>
                                </li>
                            }*@
                    </ul>
                    <ul class="nav navbar-nav ml-auto">
                        <partial name="_LoginPartial.cshtml" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @if (ViewBag.ContainerFluid == true)
    {
        <div>
            @RenderBody()
        </div>
    }
    else
    {
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }


    @*<footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - Light Apartment
            </div>
        </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/DataTables/datatables.min.js"></script>
    <script src="~/lib/sweetalert/lib/sweet-alert.js"></script>
    <script src="~/js/SweetAlertHelper.js"></script>
    <script src="~/lib/select2.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>