ManagementApartments/Controllers/ApartmentsController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using ManagementApartments.Data.Models;
using ManagementApartments.Data.Service.Interface;
using X.PagedList;
using ManagementApartments.Data.Config;
using Microsoft.AspNetCore.Http;
using System.IO;
using ManagementApartments.Data.DTO;
using AutoMapper;

namespace ManagementApartments.Controllers
{
    public class ApartmentsController : Controller
    {
        private readonly IApartmentsService apartmentService;
        private readonly IMapper mapper;

        public ApartmentsController(IApartmentsService apartmentService,IMapper mapper)
        {
            this.apartmentService = apartmentService;
            this.mapper = mapper;
        }

        // GET: Apartments
        public IActionResult Index(int page = 1)
        {
            IPagedList<Apartment> apartments = apartmentService.GetByPage(page, 9, this.User.GetLoggedInUserId<string>());
            return View(apartments);
        }

        // GET: Apartments/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>(); 
            return View();
        }

        // POST: Apartments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,Description,ApartmentPrice,RentPrice,Area")] ApartmentCreateDTO apartment)
        {
            if (ModelState.IsValid)
            {
                apartmentService.Create(apartment, this.User.GetLoggedInUserId<string>());
                return RedirectToAction(nameof(Index));
            }

            return View(mapper.Map<ApartmentCreateDTO, Apartment>(apartment));
        }

        public ActionResult SaveImage(IFormFile file, int apartmentId)
        {
            if (file != null)
            {
                string extension = Path.GetExtension(file.FileName);

                List<string> allowedExtensions = new List<string>()
                {
                    ".png", ".bmp", ".svg", ".jpg", ".jpeg", ".gif"
                };

                if (!allowedExtensions.Contains(extension))
                {
                    return Json(new SaveImageFeedbackDTO
                    {
                        StatusSuccess = false,
                        Message = "Only .png .bmp .svg .jpg .jpeg .gif file types are allowed",
                        Title = "File type not supported."
                    });
                }
                string logoAsBase64 = this.apartmentService.SaveImage(file, apartmentId);

                return Json(new SaveImageFeedbackDTO
                {
                    StatusSuccess = true,
                    LogoAsBase64 = logoAsBase64
                });
            }
            else
            {
                return Json(new SaveImageFeedbackDTO
                {
                    StatusSuccess = false,
                    Message = "Only .png .bmp .svg .jpg .jpeg .gif file types are allowed",
                    Title = "File type not supported."
                });
            }
        }

        public ActionResult DeleteLogo(int apartmentId)
        {
            this.apartmentService.DeleteLogo(apartmentId);

            return Json(true);
        }

        // GET: Apartments/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apartment = this.apartmentService.Get(id??0, this.User.GetLoggedInUserId<string>());
            ViewData["ApplicationUserId"] = this.User.GetLoggedInUserId<string>();
            return View(apartment);
        }

        // POST: Apartments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,Name,Description,ApartmentPrice,RentPrice,Area")] ApartmentCreateDTO apartmentDto)
        {
            if (id != apartmentDto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                apartmentService.Edit(apartmentDto, this.User.GetLoggedInUserId<string>());
                return RedirectToAction(nameof(Index));
            }
            
            return View(apartmentService.Get(apartmentDto.Id, this.User.GetLoggedInUserId<string>()));
        }

        // GET: Apartments/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apartment = this.apartmentService.Get(id ?? 0, this.User.GetLoggedInUserId<string>()); 
            return View(apartment);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            apartmentService.Remove(id, this.User.GetLoggedInUserId<string>());
            return RedirectToAction(nameof(Index));
        }
    }
}

ManagementApartments/Controllers/EquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManagementApartments.Data;
using ManagementApartments.Data.Models;
using ManagementApartments.Data.Service.Interface;

namespace ManagementApartments.Controllers
{
    public class EquipmentsController : Controller
    {
        private readonly ManagementApartmentDbContext _context;
        private readonly IEquipmentsService equipmentsService;

        public EquipmentsController(ManagementApartmentDbContext context, IEquipmentsService equipmentsService)
        {
            _context = context;
            this.equipmentsService = equipmentsService;
        }

        // GET: Equipments
        public async Task<IActionResult> Index()
        {
            var managementApartmentDbContext = _context.Equipment.Include(e => e.Room);
            return View(await managementApartmentDbContext.ToListAsync());
        }


        public ActionResult GetList(int roomId)
        {
            return Json(new { data = equipmentsService.GetList(roomId) });
        }

        // GET: Equipments/Create
        public IActionResult Create(int roomId)
        {
            ViewData["RoomId"] = roomId;
            return View();
        }

        // POST: Equipments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Price,RoomId")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                equipmentsService.Create(equipment);
                return RedirectToAction("Edit", "Rooms", new { id = equipment.RoomId });
            }
            ViewData["RoomId"] = equipment.RoomId;
            return View(equipment);
        }

        // GET: Equipments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = equipmentsService.Get(id ?? 0);
            if (equipment == null)
            {
                return NotFound();
            }
            ViewData["RoomId"] = equipment.RoomId;
            return View(equipment);
        }

        // POST: Equipments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Price,RoomId")] Equipment equipment)
        {
            if (id != equipment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                equipmentsService.Update(equipment);
                return RedirectToAction("Edit", "Rooms", new { id = equipment.RoomId });
            }
            ViewData["RoomId"] = equipment.RoomId;
            return View(equipment);
        }

        // GET: Equipments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipment = equipmentsService.Get(id ?? 0);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // POST: Equipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var equipment = equipmentsService.Get(id);
            equipmentsService.Remove(id);
            return RedirectToAction("Edit", "Rooms", new { id = equipment.RoomId});
        }

        private bool EquipmentExists(int id)
        {
            return _context.Equipment.Any(e => e.Id == id);
        }
    }
}

ManagementApartments/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ManagementApartments.Data;
using ManagementApartments.Data.Models;
using ManagementApartments.Data.Service.Interface;
using ManagementApartments.Data.Config;

namespace ManagementApartments.Controllers
{
    public class RoomsController : Controller
    {
        private readonly ManagementApartmentDbContext _context;
        private readonly IRoomService roomService;

        public RoomsController(ManagementApartmentDbContext context, IRoomService roomService)
        {
            _context = context;
            this.roomService = roomService;
        }

        public ActionResult GetList(int apartmentId)
        {
            return Json(new { data = roomService.GetList(apartmentId) });
        }

        // GET: Rooms/Create
        public IActionResult Create(int apartmentId)
        {
            ViewData["ApartmentId"] = apartmentId;
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Name,RoomStyle,Area,ApartmentId")] Room room)
        {
            if (ModelState.IsValid)
            {
                roomService.Create(room);
                return RedirectToAction("Edit","Apartments",new { id = room.ApartmentId});
            }
            ViewData["ApartmentId"] = room.ApartmentId;
            return View(room);
        }

        // GET: Rooms/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = roomService.Get(id??0);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["ApartmentId"] = room.ApartmentId;
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,RoomStyle,Area,ApartmentId")] Room room)
        {
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                roomService.Update(room);
                return RedirectToAction("Edit", "Apartments", new { id = room.ApartmentId });
            }
            ViewData["ApartmentId"] = room.ApartmentId;
            return View(room);
        }

        // GET: Rooms/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = roomService.Get(id?? 0);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var room = roomService.Get(id);
            roomService.Remove(id);
            return RedirectToAction("Edit", "Apartments", new { id = room.ApartmentId });
        }

    }
}

ManagementApartments/Views/Rooms/Create.cshtml
@model ManagementApartments.Data.Models.Room

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomStyle" class="control-label"></label>
                <input asp-for="RoomStyle" class="form-control" />
                <span asp-validation-for="RoomStyle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <input asp-for="ApartmentId" style="display:none" value="@ViewBag.ApartmentId" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" href="@Url.Action("Edit","Apartments",new { Id = ViewBag.ApartmentId})">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ManagementApartments/Views/Rooms/Delete.cshtml
@model ManagementApartments.Data.Models.Room

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomStyle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomStyle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-primary" href="@Url.Action("Edit","Apartments",new {id = Model.ApartmentId })">Back to List</a>
    </form>
</div>

ManagementApartments/Views/Rooms/Details.cshtml
@model ManagementApartments.Data.Models.Room

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomStyle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomStyle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Area)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Area)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apartment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apartment.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ManagementApartments/Views/Rooms/Edit.cshtml
@model ManagementApartments.Data.Models.Room

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Room</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomStyle" class="control-label"></label>
                <input asp-for="RoomStyle" class="form-control" />
                <span asp-validation-for="RoomStyle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Area" class="control-label"></label>
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
            <input asp-for="ApartmentId" style="display:none" value="@ViewBag.ApartmentId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<a class="btn btn-primary mt-5 mb-1" href="@Url.Action("Create","Equipments",new {roomId = Model.Id })">Add equipment</a>

<table id="equipmentsTable" class="display" data-room-id="@Model.Id" data-request-url="@Url.Action("GetList", "Equipments")">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Price</th>
            <th></th>
        </tr>
    </thead>
</table>

<div>
    <a class="btn btn-primary" href="@Url.Action("Edit","Apartments",new { Id = ViewBag.ApartmentId})">Back to Apartments</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/Rooms/RoomsEditController.js"></script>
}

ManagementApartments/Views/Rooms/Index.cshtml
@model IEnumerable<ManagementApartments.Data.Models.Room>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoomStyle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Area)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apartment)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoomStyle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apartment.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>